{
 "title": "States",
 "description": "Covid-19 Stats for US States",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "State",
    "query": "select distinct(state) from us_states"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cases for $State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us_states\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Total Deaths for $State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us_states\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Cases/Day for $State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate AS \"rate\"\nFROM us_states_case_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,7d),\n  avg(rate) AS \"Avg\"\nFROM us_states_case_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nGROUP BY 1\nORDER BY $__timeGroup(date_time,7d)"
    }
   ]
  },
  {
   "title": "Deaths/Day for $State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate\nFROM us_states_death_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,7d),\n  avg(rate) AS \"Avg\"\nFROM us_states_death_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nGROUP BY 1\nORDER BY $__timeGroup(date_time,7d)"
    }
   ]
  },
  {
   "title": "Cases for $State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us_states\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Deaths for $State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us_states\nWHERE\n  $__timeFilter(date_time) AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  }
 ]
}