{
 "title": "United States of America",
 "description": "Covid-19 Stats for the United States of America",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "United States Covid Cases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "United States Covid Deaths",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "United States Covid Cases/Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate\nFROM us_case_rate_vw\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,7d),\n  avg(rate) AS \"Avg\"\nFROM us_case_rate_vw\nWHERE\n  $__timeFilter(date_time)\nGROUP BY 1\nORDER BY $__timeGroup(date_time,7d)"
    }
   ]
  },
  {
   "title": "United States Covid Deaths/Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate\nFROM us_death_rate_vw\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,7d),\n  avg(rate) AS \"Avg\"\nFROM us_death_rate_vw\nWHERE\n  $__timeFilter(date_time)\nGROUP BY 1\nORDER BY $__timeGroup(date_time,7d)"
    }
   ]
  },
  {
   "title": "United States Covid Cases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "United States Covid Deaths",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  }
 ]
}