{
 "title": "US Counties",
 "description": "Covid-19 Stats for US Counties",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "State",
    "query": "select distinct(state) from us_states"
   },
   {
    "name": "County",
    "query": "select distinct(county) from us_counties where state = '$State'"
   }
  ]
 },
 "panels": [
  {
   "title": "Cases for $County",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us_counties\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Deaths for $County",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us_counties\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Cases for $County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  cases\nFROM us_counties\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Deaths for $County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  deaths\nFROM us_counties\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Cases per Day for $County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate\nFROM us_county_case_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,7d),\n  avg(rate) AS \"Avg\"\nFROM us_county_case_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County'\nGROUP BY 1\nORDER BY $__timeGroup(date_time,7d)"
    }
   ]
  },
  {
   "title": "Deaths per Day for $County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  rate\nFROM us_county_death_rate_vw\nWHERE\n  $__timeFilter(date_time) AND\n  county = '$County' AND\n  state = '$State'\nORDER BY date_time"
    }
   ]
  }
 ]
}